### PR TITLE
Custom processing data

### PR DESCRIPTION
**Pull request by eikek**
Allows to add some custom arbitrary json to the upload request which then gets passed through processing and ends up in the notification request. The intention is that addons and event consumers can use it for post processing.

Refs: #2334

### CODE REVIEW

**Comment by eikek** [comment]
I think this should close #2334 as it allows to pass custom stuff to the upload request and get it back as the output of the processing task (and it is made available to addons). It does only work for upload request, it doesn't work when reprocessing an item (nor with the scan-mailbox task).

**Comment by madduck** [comment]
I've tested this and can confirm that the data arrive at the addon just like one would expect.

Did we duplicate work with @v6ak on this, or did you guys work together?

**Comment by eikek** [comment]
All good from my side

**Comment by v6ak** [comment]
I've looked at the differences in order to learn from it. Aside of trivial differences (naming / argument order / temporary code for debugging) and one [unrelated commit](https://github.com/eikek/docspell/pull/2380/commits/175ae0299667c84774ef482917ac958a9adc9700)), there are some other differences:
* class NewFile.Meta – IIUC this adds the option to add custom metadata also by some addon
* class NewItem.Meta – IIUC this adds the option to add custom metadata also by some addon
* **class ItemData** – @eikek's version adds a field there, my doesn't. I am not sure why this is needed. It seems to work even without it, but maybe I am missing some scenario. Maybe that's what Eike has told me on Monday about saving in the DB.
* Some examples
* Eike's code supports Json (as he has modified and updated the OpenAPI plugin), not just String.

**Pull request merged**
