### PR TITLE
Use http4s' new Part.filename method

### LINKED ISSUE #2825: Broken Text-Encoding in Filenames after Upload
I noticed this recently, but not sure when exactly this started happening, possibly with the 0.42 update.

Any german Umlaute are affected by this, but I assume this might be a general UTF-8 encoding issue.

Here it is in the upload form before uploading:
image

Here is the document after uploading without modifying it:
image

I feels like a classic case of interpreting UTF-8 as ASCII/ISO 8859-1 on the byte level.

### PR DESCRIPTION
**Pull request by pschichtel**
this reencodes the filename as UTF-8, which is probably a safe bet.

this should close #2825

### CODE REVIEW

**Comment by nekrondev** [comment]
LGTM 👍

**Comment by pschichtel** [comment]
@eikek could you have a look at this?

**Comment by eikek** [comment]
Thank you and sorry for the delay. I'm having a bit of a hard time currently. I'll be slow to respond for a while, hopefully starting better next year ;-)

**Comment by pschichtel** [comment]
Unfortunate that ci files, I think I had that issue earlier but it somehow disappeared. I'll fix that in the coming days

**Comment by pschichtel** [comment]
@eikek fixed and rebased this

**Pull request merged**
