### PR TITLE
Proper docker files (build from code) - 2.0

### PR DESCRIPTION
**Pull request by totti4ever**
As asked in #283, I setup the dockerfiles to build from the actual code, not from releases.

This enables especially using the latest snapshot as docker image easily.

Idea of this fundamental rework of the dockerfiles is:

* Base image with all binaries (make, make-zip, make-tools)
* Dependant image for all three sub-images (restserver, joex, consumedir)
* build scripts reduced to one for building and one for pushing - they derive themselves whether it is a snapshot or a tagged version
* plus I added (basic) health checks

this PR replaces #288 

----

new file:      base.dockerfile
	base docker file for compiling sources

deleted:       build-images.sh
	replaced by dev-build-images.sh

deleted:       build-joex-base.sh
	replaced by base / joex dockerfile

changed:       consumedir.dockerfile
	based on compiled tool-binaries from base image
	added health check (basic, check for REST server connection)

new file:     dev-build-images.sh
	added one build script for all purposes
	derives tag from version-file (all snapshot become latest)

new file:     dev-push-images.sh
	added one push script for all purposes (similar to build)

changed:       docker-compose.yml
	changed regarding entrypoints and commands now being in the images
	added health checks for 3rd party images (postgres and solr)
	some minor renaming of the areas

renamed:      entrypoint-joex.sh -> joex-entrypoint.sh
	for better order

renamed:      joex-base.dockerfile -> joex.dockerfile
	also reworked to base on main base image
	plus renamed for better order

deleted:       push-images.sh
	replaced by dev-push-images.sh

deleted:       push-joex-base.sh
	not necessary anymore

changed:       restserver.dockerfile
	reworked to be base on main base image
	smaller
	added health check

### CODE REVIEW

**Comment by eikek** [comment]
Wow, that's great – thank you! I'm going to take a deeper look when I have more time (as I want to better understand this :)).

One thing I noticed now: the joex-base image with all the required tools is gone now, right? I extracted the base image for joex only, because I always had problems creating the image due to ocrmypdf. The package from alpine, for example, doesn't work (it installs, but throws runtime errors when being used). Then installing it via pip was also a trial-and-error process…. It's fine for me like that, just letting you know about my problems. Maybe we should test the image with some pdf file

**Comment by totti4ever** [comment]
> Wow, that's great – thank you! I'm going to take a deeper look when I have more time (as I want to better understand this :)).

Please ask any question you want - I am no Docker mastermind, so the question might help to improve the code ;-)
 

> One thing I noticed now: the joex-base image with all the required tools is gone now, right? I extracted the base image for joex only, because I always had problems creating the image due to ocrmypdf. The package from alpine, for example, doesn't work (it installs, but throws runtime errors when being used). Then installing it via pip was also a trial-and-error process…. It's fine for me like that, just letting you know about my problems. Maybe we should test the image with some pdf file

- [x] Test pdf (totti4ever)
Did send a pdf without text and had no problems. If you come up with problems, we could just use the official [dockerfile](https://github.com/jbarlow83/OCRmyPDF/blob/master/.docker/Dockerfile) of ocrmypdf or even call the official docker image from docspell's image. But please, check yourself!
  - [ ] Check ocrmypdf (eikek)


----
_from old PR (#288)_

> How do I create the images now? For example, when I want to start from some branch, what do I need to do? Maybe we could provide a simple script or something to get started?

- [x] `dev-build-images.sh` (building all images), `dev-push-images.sh` (pushing the three of them)
Just call them form the branch. Version number comes from `version.sbt`, snapshots become `latest`

> This now builds the application inside a docker container, right? This is really nice and I love the idea to just spin up a docker container with any version. Otoh, for releases I'd like to use the exact same zip file that is uploaded to github (because that is the one I do some tests with). How does this work now? I simply use the existing dockerfiles as before, right?
- [x] All is built during docker image build, exactly. The result should be the exact same binaries as you upload to github. Although, I just figured out today that we might have differences due to versioning differing of ELM, SBT, ... - but shouldn't really make a difference.
  - [ ] Do you want me to compare the MD5 checksum?

> What do you think about putting your new files into some subdirectory? Are they all self-contained – or do they somehow use existing files? If self-contained, maybe a subdir would be more readable?
- [ ] decide on whether existing file are replaced or we keep two docker build pipelines
I am strongly advising to replace the old ones! If you have any doubts, let's move them away, but let's do not keep two different file structures!

**Comment by eikek** [comment]
> Please ask any question you want - I am no Docker mastermind, so the question might help to improve the code ;-)

So here are some noob questions. Thanks for clarifying!
- the base image shows a lot of separate RUN calls. Why is this? I can imagine that this image is only used as a base and the layers in there don't count for the "real" images?
- you changed the "tag names", for example : `docspell:restserver-latest` to `docspell-restserver:latest`. This is much better, of course. But doesn't it mean that I have to setup other "projects" now on docker-hub?
 
> > One thing I noticed now: the joex-base image with all the required tools is gone now, right? I extracted the base image for joex only, because I always had problems creating the image due to ocrmypdf. The package from alpine, for example, doesn't work (it installs, but throws runtime errors when being used). Then installing it via pip was also a trial-and-error process…. It's fine for me like that, just letting you know about my problems. Maybe we should test the image with some pdf file
> 
>     * [x]  Test pdf (totti4ever)
>       Did send a pdf without text and had no problems. If you come up with problems, we could just use the official [dockerfile](https://github.com/jbarlow83/OCRmyPDF/blob/master/.docker/Dockerfile) of ocrmypdf or even call the official docker image from docspell's image. But please, check yourself!

That's fair enough! It's just that I remember times where creating the release took me 5 minutes and teh docker image >1h, because of fiddling with ocrmypdf. And it doesn't come up at build time, you'll need to test the app to realize that it is broken. I have no clue how to integrate multiple docker files (like the base image + ocrmypdf dockerfile). Is it ok to ping you if this would come up?

>       * [ ]  Check ocrmypdf (eikek)

I'm just running the build-image script  :-)

> _from old PR (#288)_
> 
> > How do I create the images now? For example, when I want to start from some branch, what do I need to do? Maybe we could provide a simple script or something to get started?
> 
>     * [x]  `dev-build-images.sh` (building all images), `dev-push-images.sh` (pushing the three of them)
>       Just call them form the branch. Version number comes from `version.sbt`, snapshots become `latest`

Nice! :+1: 
 
> > This now builds the application inside a docker container, right? This is really nice and I love the idea to just spin up a docker container with any version. Otoh, for releases I'd like to use the exact same zip file that is uploaded to github (because that is the one I do some tests with). How does this work now? I simply use the existing dockerfiles as before, right?
> 
>     * [x]  All is built during docker image build, exactly. The result should be the exact same binaries as you upload to github. Although, I just figured out today that we might have differences due to versioning differing of ELM, SBT, ... - but shouldn't really make a difference.
>       
>       * [ ]  Do you want me to compare the MD5 checksum?

No, this is not necessary, as I don't want to keep them "the same". I don't think they will match anyways. There is also the build-time included somewhere, so the artifacts will be different. That is ok, because they are also build using different setups. The java version may be different, for example. All of that shouldn't really matter. If there is the goal to have them the same, I think there is no other option than really using the same artifacts.

But I'm fine with having different artifacts. Only thing I need is a easy and convenient way to build a release and push it to dockerhub. 


> > What do you think about putting your new files into some subdirectory? Are they all self-contained – or do they somehow use existing files? If self-contained, maybe a subdir would be more readable?
> 
>     * [ ]  decide on whether existing file are replaced or we keep two docker build pipelines
>       I am strongly advising to replace the old ones! If you have any doubts, let's move them away, but let's do not keep two different file structures!

Now with this PR I totally agree. There shouldn't be two things to maintain! i simply wasn't sure about the goal from the last PR.

**Comment by eikek** [comment]
I have some more questions…:-)

IIUC it's now almost the same as before, only that the artifacts are coming from another docker image that has been build before?

For the joex component, wouldn't it be possible to use for `FROM` the "old" joex-base image and copy the artifact from the build image? Now it uses alpine base image and installs all the tools everytime I build joex, not? The advantage I see is that I don't need to transfer 1.4g to dockerhub all the time, but only ~300M (the overall image is of course not smaller) and it would be possible to separately upgrade the tools. Docker is not reproducible, so everyday I run `docker build` it may create a different image. Using the old joex-base was my attempt to fix it a bit. This were my thoughts for creating this joex-base image, not sure if this breaks best practices with docker.

I already wrote about the new image names: `docspell:restserver-latest` vs `dockspell-restservet:latest`. What was your intention in changing these? It looks better to me, but the problem is, if I merge this, the documentation doesn't work anymore. Users trying docspell with the documented docker way won't be able to. If the names were the same, we could merge this and use this docker line for the next release. Another point, where I may be completely wrong, is that I think I need to create different namespaces/projects (whatever they call it) on docker hub?

**Comment by totti4ever** [comment]
> - the base image shows a lot of separate RUN calls. Why is this? I can imagine that this image is only used as a base and the layers in there don't count for the "real" images?

Exactly, that means you can combine smaller fallback steps during build with smaller final images

> - you changed the "tag names", for example : `docspell:restserver-latest` to `docspell-restserver:latest`. This is much better, of course. But doesn't it mean that I have to setup other "projects" now on docker-hub?

> I already wrote about the new image names: docspell:restserver-latest vs dockspell-restservet:latest. What was your intention in changing these? It looks better to me, but the problem is, if I merge this, the documentation doesn't work anymore. Users trying docspell with the documented docker way won't be able to. If the names were the same, we could merge this and use this docker line for the next release. Another point, where I may be completely wrong, is that I think I need to create different namespaces/projects (whatever they call it) on docker hub?


- Yes, most probably one has to setup new repos/namespaces on Docker Hub. This shouldn't have any impact on the decision as this is one time only. 
- Intention was to have them used in the way they are thought, which is image:version. And restserver vs consumedir is rather a different module than a different version. 
- By documentation you are also talking about the one time changes regarding using docker? Shouldn't make an impact from my point of view either. But ...
- Of course people using it the current way will face a breaking change and have to adapt their setup.
Not the best thing, but breaking changes happen

In the end, it's technically not a really big difference and it's your project. So just decide which way you wanna go; I'm in one way or the other!
 

> Is it ok to ping you if this would come up?

sure, I'll stay tuned ;-)


----

> IIUC it's now almost the same as before, only that the artifacts are coming from another docker image that has been build before?

yes, which means you can 
1. build images with local changes only 
2. build images of the current master, i.e. untagged

> For the joex component, wouldn't it be possible to use for FROM the "old" joex-base image and copy the artifact from the build image? Now it uses alpine base image and installs all the tools everytime I build joex, not? The advantage I see is that I don't need to transfer 1.4g to dockerhub all the time, but only ~300M (the overall image is of course not smaller) and it would be possible to separately upgrade the tools. Docker is not reproducible, so everyday I run docker build it may create a different image. Using the old joex-base was my attempt to fix it a bit. This were my thoughts for creating this joex-base image, not sure if this breaks best practices with docker.

Actually by having the copy from base quite late, the steps before shouldn't rebuild all the time, but stay in cache. Doesn't this happen for you? I should have a look.
I still like the idea of having separate base images (would be another point for the separate docker repos from my point of view then), to be able to build them independently.


> Edit: The base image seems to always get the source from github, but the bash script reads the version from the current working directory? Shouldn't the sources somehow be copied to the build image from the current working dir? Or how would i build a release for example?

Ha, yes. This is something, which came to my mind when doing my own code review myself, check the code comments. I have to rework that, so that you either go to github (remote build) or to the local code (and then do not use github). The latter one would also help to build local changes without committing!

> Edit2: I just read about multistage builds. So you can ignore now my first question in the last comment :-)

too late. Read about it only the last couple of days as well myself :-)

**Comment by eikek** [comment]
> > * you changed the "tag names", for example : `docspell:restserver-latest` to `docspell-restserver:latest`. This is much better, of course. But doesn't it mean that I have to setup other "projects" now on docker-hub?
> 
> > I already wrote about the new image names: docspell:restserver-latest vs dockspell-restservet:latest. What was your intention in changing these? It looks better to me, but the problem is, if I merge this, the documentation doesn't work anymore. Users trying docspell with the documented docker way won't be able to. If the names were the same, we could merge this and use this docker line for the next release. Another point, where I may be completely wrong, is that I think I need to create different namespaces/projects (whatever they call it) on docker hub?
> 
>     * Yes, most probably one has to setup new repos/namespaces on Docker Hub. This shouldn't have any impact on the decision as this is one time only.
> 
>     * Intention was to have them used in the way they are thought, which is image:version. And restserver vs consumedir is rather a different module than a different version.
> 
>     * By documentation you are also talking about the one time changes regarding using docker? Shouldn't make an impact from my point of view either. But ...
> 
>     * Of course people using it the current way will face a breaking change and have to adapt their setup.
>       Not the best thing, but breaking changes happen
>
> In the end, it's technically not a really big difference and it's your project. So just decide which way you wanna go; I'm in one way or the other!

Ok, I see your points. It's also ok to have breaking changes sometimes. If you don't mind I'd prefer to keep them all under the "docspell" project for now.
 
> > Is it ok to ping you if this would come up?
> 
> sure, I'll stay tuned ;-)

Thank you!

> > IIUC it's now almost the same as before, only that the artifacts are coming from another docker image that has been build before?
> 
> yes, which means you can
> 
>     1. build images with local changes only
> 
>     2. build images of the current master, i.e. untagged
> 
> 
> > For the joex component, wouldn't it be possible to use for FROM the "old" joex-base image and copy the artifact from the build image? Now it uses alpine base image and installs all the tools everytime I build joex, not? The advantage I see is that I don't need to transfer 1.4g to dockerhub all the time, but only ~300M (the overall image is of course not smaller) and it would be possible to separately upgrade the tools. Docker is not reproducible, so everyday I run docker build it may create a different image. Using the old joex-base was my attempt to fix it a bit. This were my thoughts for creating this joex-base image, not sure if this breaks best practices with docker.
> 
> Actually by having the copy from base quite late, the steps before shouldn't rebuild all the time, but stay in cache. Doesn't this happen for you? I should have a look.
> I still like the idea of having separate base images (would be another point for the separate docker repos from my point of view then), to be able to build them independently.

Last time I tried (using the old dockerfiles), it wasn't the case. I ran into problems with the packages everytime I did a release. But I guess the alpine image changed during the few weeks.

**Pull request merged**
