### PR TITLE
Replace `http4s-blaze-client` with `http4s-ember-client`.

### LINKED ISSUE #2221: Replace blaze with ember
The [blaze](https://github.com/http4s/blaze) http library is superseded by [ember](https://github.com/http4s/http4s/tree/series/0.23/ember-core).

### PR DESCRIPTION
**Pull request by rehanone**
This fixes  #2221. The issue is marked complex so I am not sure if I missed something so please provide feedback.

### CODE REVIEW

**Comment by eikek** [comment]
Thank you very much! This is one part of the issue. There is the server part left, which is probably a bit more complex to adapt.

**Comment by rehanone** [comment]
Yes I realized that and stared working on it. But I did not commit that change as it is a bit big and might require some additional testing.

**Comment by eikek** [comment]
> Possibly, that could be a separate PR.

Yes sure! Thanks a lot for looking into this!

**Comment by rehanone** [comment]
I think the build failed due to scalafix errors. I have fixed it.

**Pull request merged**
