### PR TITLE
Adding CJK and Custom Mapping Documentation

### PR DESCRIPTION
**Pull request by tenpai-git**
This resolves https://github.com/eikek/docspell/issues/2667 item 3 to add documentation for custom mapping documentation and follow-ups for working with vertical language outputs.

### CODE REVIEW

**Comment by eikek** [comment]
Hi @tenpai-git - since this feature is part of the _next_ release, this documentation update should target the master branch. As you can see, this PR contains many commits from master, that you didn't create :-) The `current-docs` branch is for documentation of the current release.

**Comment by tenpai-git** [comment]
Sorry about that @eikek - I switched to the correct target now! I was targeting current-docs last time because of the last documentation I worked on, but in hindsight, that was to resolve an issue in the current release and like you said this is for next release. 

Should be good now!

**Comment by eikek** [comment]
No reason to be sorry! Thanks for updating. If you think this is now good to go, I'll try to find some time to do the next release.

**Comment by tenpai-git** [comment]
Yup, it should be all good as far as I can tell. Can come back to vertical Korean/Chinese at a later point or another person proficient in those languages can easily use this as a basis to add them.

**Pull request merged**
