### PR TITLE
Add support for Slovak language

### PR DESCRIPTION
**Pull request by mprasil**
Just the basic support was added following examples for other languages. Apologies in advance for any errors, I'm very unfamiliar with Scala/Elm.

### CODE REVIEW

**Comment by mprasil** [comment]
Thanks for feedback. I can't seem to get my local environment into a state where it would run `sbt fix` successfully. So I'm afraid I'll need your assistance here. The branch should be writable by you, so feel free to push the fix.

**Comment by eikek** [comment]
I tried to add to your branch, but I don't have the permissions. I might cherry pick your commit or if you can get your setup working again, would be nice to run  a `sbt fix` and push the result.

**Comment by mprasil** [comment]
Thanks for looking into this, I have checked the "allow edits by maintainers":

image

I believe this should let you push to the `add-slovak-language-support` branch. (You will have to push to this branch tho, AFAIK you will not be able to push elsewhere)

**Comment by mprasil** [comment]
@eikek I finally managed to get my local setup in good enough shape to apply sbt fix. It only required learning Nix. 😅

Seriously though, apologies for the delay. I only managed back to this now. Hopefully this fixes the issues reported by CI.

**Comment by eikek** [comment]
Thank you very much @mprasil and never worry about anything time-wise - here is no hurry ever :) I also didn't find the time to do it.

**Pull request merged**
